steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent', '.']

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'help-desk-agent'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--service-account'
  - 'agentaidesk-app@agentaidesk-2025.iam.gserviceaccount.com'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'GCP_PROJECT_ID=$PROJECT_ID,STORAGE_BUCKET=agentaidesk-storage-2025,DEEPSEEK_API_KEY=sk-7c38538a7465446ba6a0bfe9da9d3565'
  - '--port'
  - '8080'
  - '--memory'
  - '1Gi'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent'
