steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'help-desk-agent'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'GCP_PROJECT_ID=$PROJECT_ID,STORAGE_BUCKET=agentaidesk-storage-2025'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/help-desk-repo/help-desk-agent'
